#!/bin/sh
JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/1.5.0/Home
ALARMS_HOME=/Users/stingleff/workspace/alarms
CLASSPATH=/Users/stingleff/workspace/alarms/target/alarms-1.0-SNAPSHOT.jar:/Users/stingleff/.m2/repository/com/mdimension/jchronic/0.2.4-SNAPSHOT/jchronic-0.2.4-SNAPSHOT.jar:/Users/stingleff/.m2/repository/org/eclipse/swt/carbon/macosx/3.4.2/macosx-3.4.2.jar
JVM_ARGS="-XstartOnFirstThread"

$JAVA_HOME/bin/java $JVM_ARGS -classpath $CLASSPATH com.milkable.alarms.Main
